---
title: "愚公移山"
date: 2025-06-09
categories: [古文]
tags: [语文]
format: html
---

## 原文：

太⾏、王屋⼆⼭，⽅七百⾥，⾼万仞，本在冀州之南，河阳之北。

北⼭愚公者，年且九⼗，⾯⼭⽽居。惩⼭北之塞，出⼊之迂也，聚室⽽谋⽈：“吾与汝毕⼒平险，指通豫南，达于汉阴，可乎？”杂然相许。其妻献疑⽈：“以君之⼒，曾不能损魁⽗之丘，如太⾏、王屋何？且焉置⼟⽯？”杂⽈：“投诸渤海之尾，隐⼟之北。”遂率⼦孙荷担者三夫，叩⽯垦壤，箕畚运于渤海之尾。邻⼈京城⽒之孀妻有遗男，始龀，跳往助之。寒暑易节，始⼀返焉。

河曲智叟笑⽽⽌之⽈：“甚矣，汝之不惠！以残年余⼒，曾不能毁⼭之⼀⽑，其如⼟⽯何？”北⼭愚公长息⽈：“汝⼼之固，固不可彻，曾不若孀妻弱⼦。虽我之死，有⼦存焉；⼦⼜⽣孙，孙⼜⽣⼦；⼦⼜有⼦，⼦⼜有孙；⼦⼦孙孙⽆穷匮也，⽽⼭不加增，何苦⽽不平？”河曲智叟亡以应。

操蛇之神闻之，惧其不已也，告之于帝。帝感其诚，命夸娥⽒⼆⼦负⼆⼭，⼀厝朔东，⼀厝雍南。⾃此，冀之南，汉之阴，⽆陇断焉。

##译文：

传说中的太行、王屋两座山（位于河南郑州），周围七百里，高七八千丈，本来在冀州南边，黄河北岸的北边。北山下面有个名叫愚公的人，年纪快到90岁了，在山的正对面居住。他苦于山区北部的阻塞，出来进去都要绕道，就召集全家人商量说：“我跟你们尽力挖平险峻的大山，（使道路）一直通到豫州南部，到达汉水南岸，可以吗？”家人纷纷表示赞同。他的妻子提出疑问说：“凭你的力气，连魁父这座小山都不能削平，能把太行、王屋怎么样呢？往哪儿搁挖下来的土和石头？”众人说：“把它扔到渤海的边上，隐土的北边。”于是愚公率领儿孙中能挑担子的三个人上了山，凿石挖土，用箕畚运到渤海边上。邻居京城氏的寡妇有个孤儿，刚七八岁，蹦蹦跳跳地去帮助他。冬夏换季，才能往返一次。河湾上的智叟讥笑愚公，阻止他干这件事，说：“你太不聪明了，你简直太愚蠢了！就凭你残余的岁月、剩下的力气连山上的一棵草都动不了，又能把泥土石头怎么样呢？”北山愚公长叹说：“你的思想真顽固，顽固得没法开窍，连孤儿寡妇都比不上。即使我死了，还有儿子在呀；儿子又生孙子，孙子又生儿子；儿子又有儿子儿子又有孙子；子子孙孙无穷无尽，可是山却不会增高加大，还怕挖不平吗？”河曲智叟无话可答。握着蛇的山神听说了这件事，怕他没完没了地挖下去，向天帝报告了。天帝被愚公的诚心感动，命令大力神夸娥氏的两个儿子背走了那两座山，一座放在朔方的东部，一座放在雍州的南部。从此以后，冀州的南部，直到汉水南岸，再也没有高山阻隔了。
